[package]
name = "cryypt_vault"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
[lints.rust]
warnings = "warn"

[[bin]]
name = "vault"
path = "src/main.rs"

[dependencies]
cryypt_cipher = { path = "../cipher" }
cryypt_common = { path = "../common" }
cryypt_compression = { path = "../compression" }
cryypt_hashing = { path = "../hashing" }
cryypt_jwt = { path = "../jwt" }
cryypt_key = { path = "../key" }
cryypt_pqcrypto = { path = "../pqcrypto" }
cryypt_quic = { path = "../quic" }

# Core dependencies
tokio = "1.47.1"
tokio-stream = "0.1.17"
futures = "0.3.31"
futures-core = "0.3.31"
futures-util = "0.3.31"
serde = "1.0.219"
serde_json = "1.0.145"
thiserror = "2.0.16"
zeroize = "1.8.1"
base64 = "0.22.1"
uuid = { version = "1.18.1", features = ["v4", "serde"] }
chrono = "0.4.41"
tracing = "0.1.41"
rand = "0.9.2"
surrealdb = { path = "../../forks/surrealdb/crates/sdk", features = ["kv-surrealkv"] }
dirs = "6.0.0"
regex = "1.11.1"
time = "0.3.41"
pin-project = "1.1.10"
secrecy = "0.10.3"
argon2 = "0.5.3"

# CLI dependencies
clap = { version = "4.5.40", features = ["derive"] }
clap_complete = "4.5.54"
dialoguer = "0.11.0"
atty = "0.2.14"
shellexpand = "3.1.1"
log = "0.4.27"
crossterm = "0.29.0"
ratatui = "0.30.0-alpha.5"

# AWS SDK dependencies
aws-config = "1.8.1"
aws-sdk-secretsmanager = "1.78.0"
cyrup_sugars = { git = "https://github.com/cyrup-ai/cyrup-sugars", branch = "main", version = "0.3.0", features = ["all"] }
fastrand = "2.3.0"
dashmap = "7.0.0-rc2"
async-stream = "0.3.6"
async_task = { path = "../async_task" }
rpassword = "7.4.0"
rand_core = { version = "0.9", features = ["os_rng"] }
getrandom = "0.3.3"
sha2 = "0.10.8"
hkdf = "0.12.4"

# RSA key format conversion (PKCS1 ↔ PKCS8/SPKI)
rsa = { version = "0.10.0-rc.4", features = ["sha2"] }

[dev-dependencies]
tempfile = "3.21.0"
