[package]
name = "cryypt_common"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
thiserror = "2.0.16"
anyhow = "1.0.98"
tracing = "0.1.41"
log = "0.4.27"
env_logger = "0.11.6"
sha2 = "0.10.9"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
backtrace = "0.3.75"
once_cell = "1.21.3"
tokio = { version = "1.47.1", features = ["sync"] }
futures = "0.3.31"
cyrup_sugars = { git = "https://github.com/cyrup-ai/cyrup-sugars", branch = "main", version = "0.3.0", features = ["all"] }

[features]
default = ["full-backtrace"]
full-backtrace = []
