[package]
name = "cryypt_quic"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
cryypt_common = { path = "../common" }
cryypt_compression = { path = "../compression" }
cryypt_cipher = { path = "../cipher" }
cryypt_key = { path = "../key" }
arc-swap = "1.7.1"
rand = "0.9.2"
zeroize = "1.8.1"
thiserror = "2.0.16"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
base64 = "0.22.1"
hex = "0.4.3"
once_cell = "1.21.3"
tokio = "1.47.1"
tokio-stream = "0.1.17"
futures = "0.3.31"
dashmap = "7.0.0-rc2"
crossbeam = "0.8.4"
p256 = "0.13.2"
hmac = "0.12.1"
base64-url = "3.0.0"
getrandom = "0.3.3"
twox-hash = "2.1.1"
hkdf = "0.12.4"
subtle = "2.6.1"
chrono = "0.4.41"
tracing = "0.1.41"
bzip2 = "0.6.0"
aes-gcm = "0.10.3"
chacha20poly1305 = "0.10.1"
sha2 = "0.10.9"
sha3 = "0.10.8"
blake2b_simd = "1.0.3"
digest = "0.10.7"
argon2 = "0.5.3"
keyring = "3.6.3"
flate2 = "1.1.2"
zstd = "0.13.3"
zip = { version = "4.2.0", default-features = false, features = ["deflate"] }
rand_core = "0.9.3"
quiche = "0.24.6"
pqcrypto = "0.18.1"
pqcrypto-mlkem = "0.1.0"
pqcrypto-mldsa = "0.1.1"
pqcrypto-falcon = "0.4.0"
pqcrypto-sphincsplus = "0.7.1"
pqcrypto-traits = "0.3.5"
uuid = "1.18.0"
bincode = "2.0.1"
cryypt_hashing = { path = "../hashing" }
cyrup_sugars = { git = "https://github.com/cyrup-ai/cyrup-sugars", branch = "main", version = "0.3.0", features = ["all"] }
tempfile = "3.14.0"
reqwest = { version = "0.11", features = ["json", "rustls-tls"], default-features = false }
rcgen = { version = "0.14.3", features = ["pem", "x509-parser"] }

# TLS and Cryptography Core
anyhow = "1.0"
rustls = { version = "0.23.31", features = ["ring"] }
rustls-native-certs = "0.8.1"
webpki-roots = "1.0.2"
rustls-pemfile = "2.2.0"
tokio-rustls = "0.26.2"

# X.509 Certificate Parsing & Validation  
x509-cert = { version = "0.2.5", features = ["builder", "pem", "sct"] }
x509-parser = "0.17.0"
x509-ocsp = "0.2.1"

# ASN.1/DER Encoding
der = { version = "0.7.10", features = ["alloc", "derive", "flagset", "oid", "pem", "real", "std"] }
const-oid = "0.9"
oid = "0.2"
spki = "0.7"

# Cryptography
ring = "0.17.14"
pem = "3.0"

# System Integration
hostname = "0.4"
simd-json = "0.15.1"
tokio-util = { version = "0.7.16", features = ["time"] }
fnv = "1.0.7"
async-trait = "0.1"

# Platform-specific dependencies
[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "3.3.0"

[dev-dependencies]
tokio = "1.47.1"
criterion = "0.7.0"
proptest = "1.7.0"
hex-literal = "1.0.0"


# Removed problematic example configuration - examples are in main examples crate
